version: '3.8'

services:
  whatsapp-bot:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 8080:8080
    volumes:
      - ./ikigai_whatsapp_bot:/app/ikigai_whatsapp_bot
    env_file:
      - .env

  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "--url=${NGROK_URL}"
      - "http://host.docker.internal:8080"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - 4040:4040
