[tool.poetry]
name = "ikigai-whatsapp-bot"
version = "0.1.0"
description = ""
authors = ["Sam Onaisi <sam.onaisi@learningplanetinstitute.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
