apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- (tpl ($.Values.commonLabels | toYaml ) $) | nindent 4 }}
  name: {{ tpl .Values.fullName . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- (tpl ($.Values.commonLabels | toYaml ) $) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- (tpl ($.Values.commonLabels | toYaml ) $) | nindent 8 }}
      annotations: {{- include "common.config.checksum" (dict "filePath" "/config.yaml" "root" $)  | nindent 8 }}
    spec:
      securityContext:
        {{- include "common.security.podSecurityContext.restricted" dict | nindent 8 }}
      containers:
      {{- with $.Values.image }}
      - image: {{ tpl (printf "%s/%s:%s" .repository .path .tag) $ }}
      {{- end }}
        imagePullPolicy: IfNotPresent
        name: ikigai-server
        ports:
        - containerPort: {{ .Values.port }}
          name: http
        livenessProbe:
          httpGet:
            port: http
            path: /health
        readinessProbe:
          httpGet:
            port: http
            path: /health
        envFrom:
        - configMapRef:
            name: {{ tpl .Values.fullName . }}
        securityContext:
          {{- include "common.security.containerSecurityContext.restricted" dict | nindent 10 }}
        resources: {{ toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: secrets
          mountPath: "/secrets"
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: {{ tpl $.Values.fullName $ }}
