name: Build image and push to registry
on:
  push:
    branches:
      - "**"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docker:
    uses: CyberCRI/github-workflows/.github/workflows/build-push.yaml@main
    with:
      registry-name: ${{ vars.DOCKER_PROD_REGISTRY }}
      image-name: ikigai-whatsapp-bot
      image-tag: ${{ github.sha }}
    secrets:
      registry-username: ${{ secrets.DOCKER_PROD_USERNAME }}
      registry-password: ${{ secrets.DOCKER_PROD_PASSWORD }}

  tag-deploy:
    needs:
      - build-docker
    uses: CyberCRI/github-workflows/.github/workflows/tag-deploy.yaml@main
